Repository ISPP-G5/NexONG_Frontend, pull requests merged in 2024-03, with the labels that each got.

#58 Bugfix/56 styles
  src/components/HeaderAdmin.js
  src/components/MenuAdmin.js
  src/screens/AdminFamily.js
  src/screens/AdminFamilyRequests.js
  src/screens/AdminPlantilla.js
  src/screens/App.js
  src/styles/admin-family.css
  src/styles/styles.css
Labels: bug, enhancement

#70 Hotfix/62-activities-screens
  src/logo/camps.jpg
  src/logo/coexistence-room.jpg
  src/logo/family-workshops.jpg
  src/logo/open-room.jpg
  src/logo/summer-club.jpg
  src/screens/Activities.js
  src/screens/Camps.js
  src/screens/CoexistenceRoom.js
  src/screens/FamilyWorkshops.js
  src/screens/OpenRoom.js
  src/screens/SummerClub.js
  src/styles/styles.css
Labels: bug

#63 Feature/50-add agenda screen and logos
  src/components/Header.js
  src/logo/agenda-logros.png
  src/logo/global-goals.png
  src/screens/Agenda.js
  src/screens/App.js
  src/styles/styles.css
Labels: enhancement

#65 Fix/42-register-and-volunteer-form-responsive
  package-lock.json
  package.json
  src/logo/google.svg
  src/screens/Register.js
  src/screens/VolunteerForm.js
  src/styles/styles.css
Labels: enhancement

#72 Feature/5-Navbar login
  src/screens/LogIn.js
Labels: enhancement

#59 Feature/51 volunteers
  src/components/Header.js
  src/logo/volunteers.bmp
  src/screens/App.js
  src/screens/Volunteers.js
Labels: enhancement

#75 Feature/11-screens-admin-events-lessons-projects-working
  src/screens/AdminClases.js
  src/screens/AdminCrearProyecto.js
  src/screens/AdminEventos.js
  src/screens/AdminProyectos.js
  src/screens/App.js
  src/styles/styles.css
Labels: enhancement

#66 feature/53-Transparency
  src/components/Header.js
  src/screens/App.js
  src/screens/Transparency.js
  src/styles/Styles.jsx
  src/styles/styles.css
Labels: enhancement

#57 Feat/57-AboutUs, history and Mision, Overviews and Values screens
  package-lock.json
  src/components/Header.js
  src/logo/actividades-jpg-01.jpg
  src/logo/sllider.png
  src/screens/AboutUs.js
  src/screens/App.js
  src/screens/Association.js
  src/screens/History.js
  src/screens/MisionOverviewValues.js
  src/styles/styles.css
Labels: enhancement

#68 Feature/54 asociationdropdown2
  src/components/Header.js
  src/screens/App.js
  src/screens/ColaboratorEntities.js
  src/screens/WhereWeAre.js
  src/styles/styles.css
Labels: enhancement

#46 Feature/40-connectionWithBack
  .env.development
  .env.production
  src/screens/HomePage.js
Labels: enhancement

#95 Feature/94-CreationVolunteersComponent
  package-lock.json
  package.json
  src/components/HeaderVolunteer.js
  src/components/MenuVolunteer.js
  src/styles/styles.css
Labels: enhancement

#96 Feature/85login
  src/components/HeaderAdmin.js
  src/screens/AdminProfile.js
  src/screens/AdminProfileUpdate.js
  src/screens/App.js
  src/screens/LogIn.js
Labels: enhancement

#98 Feature/97 educators component
  src/components/EducatorsLayout.js
  src/components/HeaderEducators.js
  src/components/MenuEducators.js
  src/screens/App.js
  src/screens/EducatorsActivities.js
  src/screens/EducatorsKidsDailyEvaluation.js
  src/screens/EducatorsKidsYearlyEvaluation.js
  src/screens/EducatorsProfile.js
  src/screens/EducatorsProileUpdate.js
  src/screens/EducatorsProyectsQuarterlyEvaluation.js
  src/screens/EducatorsProyectsYearlyEvaluation.js
  src/styles/styles.css
Labels: enhancement

#106 Fix/99-agenda
  src/logo/agenda2030/agenda-header.png
  src/logo/agenda2030/agenda-logros.png
  src/logo/agenda2030/agua.png
  src/logo/agenda2030/alianzas.png
  src/logo/agenda2030/ciudades.png
  src/logo/agenda2030/clima.png
  src/logo/agenda2030/desigualdades.png
  src/logo/agenda2030/educacion.png
  src/logo/agenda2030/hambre.png
  src/logo/agenda2030/igualdad.png
  src/logo/agenda2030/innovacion.png
  src/logo/agenda2030/paz.png
  src/logo/agenda2030/plan-accion-social.png
  src/logo/agenda2030/pobreza.png
  src/logo/agenda2030/produccion.png
  src/logo/agenda2030/salud.png
  src/logo/agenda2030/submarina.png
  src/logo/agenda2030/terrestres.png
  src/logo/agenda2030/trabajo.png
  src/screens/Agenda.js
  src/styles/styles.css
Labels: bug

#105 Feature/90-VolunteersAgenda
  src/screens/App.js
  src/screens/VolunteerAgenda.js
  src/styles/styles.css
Labels: enhancement

#38 Feature/38-pantalla admin Voluntarios y educadores
  package-lock.json
  package.json
  src/components/PeopleCard.js
  src/components/ShowVolunteersAndEducators.js
  src/screens/AdminEducadores.js
  src/screens/AdminEducadoresAdd.js
  src/screens/AdminVoluntarios.js
  src/screens/AdminVolunteersAdd.js
  src/screens/App.js
  src/styles/styles.css
Labels: enhancement

#35 Feature/35-Pantalla-admin-socios
  package-lock.json
  package.json
  src/screens/AdminAsamblea.js
  src/screens/AdminSocios.js
  src/screens/App.js
  src/styles/styles.css
Labels: enhancement

#104 Feature/102-Kids-Evaluation
  package-lock.json
  package.json
  src/components/FamilyCard.js
  src/components/StudentsCard.js
  src/screens/App.js
  src/screens/EducatorsKidsDailyEvaluation.js
  src/screens/EducatorsKidsYearlyEvaluation.js
  src/screens/LogIn.js
  src/styles/styles.css
Labels: enhancement

#111 Fix/101-admin-families
  src/screens/AdminFamily.js
Labels: bug

#110 Fix/84-create-classes-events-projects
  src/components/AdminApiErrors.js
  src/components/AdminLessonForm.js
  src/screens/AdminClases.js
  src/screens/AdminCreateLesson.js
  src/screens/AdminEditarClase.js
  src/screens/AdminEventos.js
  src/screens/App.js
  src/styles/styles.css
Labels: bug

#113 Feature/80-navbar-donations
  src/components/Header.js
  src/screens/Donation.js
  src/styles/styles.css
Labels: enhancement

#135 fix/129-admin-families
  src/components/PersonCard.js
  src/components/ShowVolunteersAndEducators.js
  src/components/useFetchData.js
  src/screens/admin/AdminFamily.js
  src/screens/admin/AdminFamilyRequests.js
Labels: bug

#136 Feature/125-educator-activity-screen
  src/components/ActivityCard.js
  src/screens/admin/AdminLessons.js
  src/screens/educators/EducatorKidsActivities.js
  src/styles/styles.css
Labels: enhancement

#137 Fix/118 admin partners
  package-lock.json
  src/components/PersonCard.js
  src/components/ShowAdminProfiles.js
  src/components/ShowVolunteersAndEducators.js
  src/components/useFetchData.js
  src/screens/admin/AdminEducators.js
  src/screens/admin/AdminFamily.js
  src/screens/admin/AdminFamilyRequests.js
  src/screens/admin/AdminPartners.js
  src/screens/admin/AdminPartnersAssembly.js
  src/screens/admin/AdminVolunteers.js
  src/screens/admin/AdminVolunteersRequests.js
  src/styles/styles.css
Labels: bug

#142 Feature/122 fix122 add educator
  src/components/PersonCard.js
  src/screens/admin/AdminEducatorsAdd.js
Labels: enhancement

#132 Fix/119-admin-event
  src/screens/admin/AdminEvents.js
Labels: bug

#140 Fix/117 educators evaluation
  src/components/Evaluation.js
  src/components/StudentEvaluation.js
  src/components/StudentsCard.js
  src/screens/educators/EducatorKidsEvaluationDaily.js
  src/screens/educators/EducatorKidsEvaluationYearly.js
  src/screens/homepage/LogIn.js
Labels: bug

#133 Feature/115 log out button header
  src/components/HeaderProfiles.js
  src/components/LogOutButton.js
  src/components/MenuProfiles.js
  src/components/Profile.js
  src/components/UpdateProfile.js
  src/screens/homepage/LogIn.js
  src/styles/styles.css
Labels: enhancement

#141 Feature/124 partners screen
  src/components/MenuProfiles.js
  src/screens/App.js
  src/screens/homepage/LogIn.js
  src/screens/partners/PartnerProfile.js
  src/screens/partners/PartnersCalendar.js
Labels: enhancement

#109 Feature/91-volunteersAttendence + Feat/128- Volunteer ageda unsubscribe
  src/screens/App.js
  src/screens/volunteers/VolunteersAttendance.js
  src/styles/styles.css
Labels: enhancement

#138 Fix/121- volunteers event
  src/screens/volunteers/VolunteerAgenda.js
Labels: bug

#139 Feature/81-Navbar suggestions
  src/screens/homepage/HomePageSuggestions.js
Labels: enhancement

#143 Feature/166-Suggestion-Admin
  src/components/MenuProfiles.js
  src/components/useFetchData.js
  src/screens/App.js
  src/screens/admin/AdminSuggestions.js
  src/styles/styles.css
Labels: enhancement

#153 Hotfix/menu
  src/components/HeaderProfiles.js
  src/components/MenuProfiles.js
  src/styles/styles.css
Labels: bug

#155 fix/150-update-images
  src/logo/backgrounds/Actividades.jpeg
  src/logo/backgrounds/Aula Abierta.jpeg
  src/logo/backgrounds/Programa Familias (2).jpeg
  src/logo/backgrounds/VOLUNTARIADO (3).JPG
  src/logo/backgrounds/Vacie.jpg
  src/logo/backgrounds/asociacion.jpg
  src/logo/backgrounds/aula de convivencia 6.jpg
  src/logo/backgrounds/colaboradores.jpg
  src/logo/backgrounds/cursoverano.jpg
  src/logo/backgrounds/historia.jpeg
  src/logo/backgrounds/nosotros.jpg
  src/logo/backgrounds/sugerencias.jpg
  src/screens/homepage/HomePageAboutUs.js
  src/screens/homepage/HomePageAssociation.js
  src/screens/homepage/HomePageColaboratorEntities.js
  src/screens/homepage/HomePageHistory.js
  src/screens/homepage/HomePageSuggestions.js
  src/styles/styles.css
Labels: enhancement

#156 Fix/144-main-page-information
  src/components/HomePageDescription.js
  src/screens/homepage/HomePage.js
Labels: bug
